// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2tE5nZJdq1f4zUwL4h1CpH81p4wzdt44',
    appId: '1:535809289690:web:2ea43b4c7b3b625225a4e3',
    messagingSenderId: '535809289690',
    projectId: 'vehical-managment',
    authDomain: 'vehical-managment.firebaseapp.com',
    storageBucket: 'vehical-managment.appspot.com',
    measurementId: 'G-6JW0PVSY6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBquhVFZHX_irCevlvqB2OGvLhNoGIr5x0',
    appId: '1:535809289690:android:d2a4e1822f0c350d25a4e3',
    messagingSenderId: '535809289690',
    projectId: 'vehical-managment',
    storageBucket: 'vehical-managment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDICCMJsIxPQZvx6RVAK1rK5mfLyWn2tvM',
    appId: '1:535809289690:ios:727e5c9b2da091b025a4e3',
    messagingSenderId: '535809289690',
    projectId: 'vehical-managment',
    storageBucket: 'vehical-managment.appspot.com',
    iosClientId: '535809289690-pof8moml006ak231spldlcpd2u8buakg.apps.googleusercontent.com',
    iosBundleId: 'com.example.vehicalManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDICCMJsIxPQZvx6RVAK1rK5mfLyWn2tvM',
    appId: '1:535809289690:ios:727e5c9b2da091b025a4e3',
    messagingSenderId: '535809289690',
    projectId: 'vehical-managment',
    storageBucket: 'vehical-managment.appspot.com',
    iosClientId: '535809289690-pof8moml006ak231spldlcpd2u8buakg.apps.googleusercontent.com',
    iosBundleId: 'com.example.vehicalManagement',
  );
}
